#!/usr/bin/env zsh

zmodload zsh/system
alias int="integer"

gen_key() {
  int keyln=$1
  unset working_num_raw
  ((keyln<8)) && {
    keyln=128
  }
  int genrnd_count=1
  local grnd_out working_num_raw
  exec {fd}< /dev/urandom
  trap "exec {fd}<&-; return 1" INT TERM
  while sysread -i $fd -s 1 working_num_raw; do
    ((grnd_out=([##16]#working_num_raw)))
    (((0x$grnd_out<0x20)) || ((0x$grnd_out>0x7e))) && {
      until (((0x$grnd_out>=0x20)) && ((0x$grnd_out<=0x7e))); do
        sysread -i $fd -s 1 working_num_raw
        ((grnd_out=([##16]#working_num_raw)))
      done
    }
    print -n "\x"$grnd_out""
    ((genrnd_count==keyln)) && {
      break
    }
    ((genrnd_count++))
  done
  exec {fd}<&-
  return 0
}

str2bin() {
  local working="$1" char
  [ -z "$working" ] && return 1
  int working_ln=${#working}
  for ((i=1; i<=$working_ln; i++)); do
    char=$working[$i]
    print -v char -n -- ${(l{8}{0})$(([##2]#char))}
    bin+="$char"
  done
}

bin2str() {
  local working="$1" char
  [ -z "$working" ] && return 1
  while true; do
    char=${working::8}
    working=${working:8}
    [ -z "$char" ] && break
    print -v char -n -- "\x"${(l{2}{0})$(([##16]2#$char))}""
    str+="$char"
  done
}

# slower but more versatile rotl/rotr (works with any arbitrary size)
do_rotl() {
  local working="$1" bin str
  int rotl_count="$2"
  ((rotl_count<=0)) && {
    rotl_count=1
  }
  [ -z "$working" ] && return 1
  str2bin "$working"
  for ((i=0; i<$rotl_count; i++)); do
    bin=""${bin:1}""${bin::1}""
  done
  bin2str "$bin"
  rotl="$str"
}

do_rotr() {
  local working="$1" bin str
  int rotr_count="$2"
  ((rotr_count<=0)) && {
    rotr_count=1
  }
  [ -z "$working" ] && return 1
  str2bin "$working"
  int rotr_ln=$((${#bin}-1))
  for ((i=0; i<rotr_count; i++)); do
    bin=""${bin:$rotr_ln}""${bin::$rotr_ln}""
  done
  bin2str "$bin"
  rotr="$str"
}

# faster but less versatile rotl/rotr (can only process 4 bytes at a time)
do_f_rotl() {
  local working="$1" decim
  int rotl_count="$2"
  ((rotl_count<=0)) && {
    rotl_count=1
  }
  local -a chars
  ((${#working}!=4)) && {
    return 1
  }
  # pack decimal values into 32 bit int
  local -i packed=$(((#working[1]<<24)|(#working[2]<<16)|(#working[3]<<8)|#working[4]))
  # perform rotation
  rotl=$((((packed<<rotl_count)|(packed>>(32-rotl_count)))&0xffffffff))
}

do_f_rotr() {
  local working="$1" decim
  int rotr_count="$2"
  ((rotr_count<=0)) && {
    rotr_count=1
  }
  local -a chars
  ((${#working}!=4)) && {
    return 1
  }
  # pack decimal values into 32 bit int
  local -i packed=$(((#working[1]<<24)|(#working[2]<<16)|(#working[3]<<8)|#working[4]))
  # perform rotation
  rotr=$((((packed>>rotr_count)|(packed<<(32-rotr_count)))&0xffffffff))
}

do_choose() {
  local num1="$1" num2="$2" num3="$3" bin str wrk
  str2bin "$num1" && num1="$bin"
  bin=''
  str2bin "$num2" && num2="$bin"
  bin=''
  str2bin "$num3" && num3="$bin"
  for ((i=0; i<${#num1}; i++)); do
    ((${num1:$i:1}==1)) && {
      wrk+=${num2:$i:1}
    } || {
      wrk+=${num3:$i:1}
    }
  done
  bin2str "$wrk"
  choose="$str"
}

do_majority() {
  local num1="$1" num2="$2" num3="$3" bin str wrk wrk2 plc
  str2bin "$num1" && num1="$bin"
  bin=''
  str2bin "$num2" && num2="$bin"
  bin=''
  str2bin "$num3" && num3="$bin"
  for ((i=0; i<${#num1}; i++)); do
    wrk2=""${num1:$i:1}""${num2:$i:1}""${num3:$i:1}""
    wrk=${wrk2//'0'/''}
    wrk=${#wrk}
    wrk2=${wrk2//'1'/''}
    wrk2=${#wrk2}
    ((wrk<wrk2)) && {
      plc+='0'
    } || {
      plc+='1'
    }
  done
  bin2str "$plc"
  majority="$str"
}

do_f_choose() {
  # expect three 32-bit (4 byte) inputs
  local num1="$1" num2="$2" num3="$3"
  choose=$((((num1&num2)^(~num1&num3))&0xffffffff))
}

do_f_majority() {
  # expect three 32-bit (4 byte) inputs
  local num1="$1" num2="$2" num3="$3"
  majority=$(((num1&num2)^(num1&num3)^(num2&num3)))
}

tumble() {
  # starting state variables (h0 through h7)
  local -a -i state=(
    0x6a09e667 # frac part of sqrt(2)
    0xbb67ae85 # frac part of sqrt(3)
    0x3c6ef372 # frac part of sqrt(5)
    0xa54ff53a # frac part of sqrt(7)
    0x510e527f # frac part of sqrt(11)
    0x9b05688c # frac part of sqrt(13)
    0x1f83d9ab # frac part of sqrt(17)
    0x5be0cd19 # frac part of sqrt(19)
  )
}

mutate_key() {
  setopt LOCAL_OPTIONS
  set +o MULTIBYTE
  # fetch key + salt
  local og_key="$1" salt="$2" newchar workingchar
  ([ -z "$salt" ] || [ -z "$og_key" ] || ((${#og_key}<8))) && {
    return 1
  }
  [ -z "$worker_id" ] && int worker_id
  # create hash sum from og_key + salt
  local key_sum=${"$(noglob print -rn -- ""$og_key""$salt""$worker_id"" | sha512sum)"%' -'}
  # XOR steps
  int salt_count salt_ln=${#key_sum}
  for ((i=0; i<${#og_key}; i++)); do
    workingchar=${og_key:$i:1}
    ((salt_count++))
    ((salt_count>salt_ln)) && {
      ((salt_count=1))
    }
    local salt_char=$key_sum[$salt_count]
    print -v newchar -n -- "\x${(l:2::0:)$(([##16]#workingchar^#salt_char))}"
    new_key+="$newchar"
  done
}

do_crypt() {
  setopt LOCAL_OPTIONS
  # fetch key name, error if key not exist
  local target_key="$1"
  local new_key
  int keystream no_write_salt
  (! [ -f "$target_key" ] && ((keystream!=1))) && {
    print "Error: key not exist"
    return 1
  }
  # read in target key from file (we can just use $(< $file) since we dont care about newline preservation on keyfile)
  ((keystream!=1)) && {
    local target_key=$(< "$target_key")
  }
  [ -z "$target_key" ] && {
    print "Error: provided key is empty"
    return 1
  }
  local target_key_ln=${#target_key}
  ((target_key_ln<8)) && {
    print "Error: key too small (must be minimum length of 8)"
    return 1
  }
  # fetch target data, error if empty
  local target_data="$2"
  [ -z "$target_data" ] && {
    print "Error: target data is empty!"
    return 1
  }
  # if data is file; read like one
  [ -f "$target_data" ] && {
    # if salt exist, use, and set no_write_salt; else gen new salt
    ((keystream!=1)) && {
      [ -f ""$target_data".salt" ] && {
        ((no_write_salt++))
        local dc_salt=$(< ""$target_data".salt")
      } || {
        local dc_salt="$(gen_key 8)"
      }
    } || {
      ((no_write_salt++))
      ([ -z "$dc_salt" ] || ((${#dc_salt}<8))) && {
        print "Error: received malformed salt"
        return 1
      }
    }
    # first key mutation
    mutate_key "$target_key" "$dc_salt"
    target_key="$new_key"
    # create temp file for storing crypt data
    [ -f ""$target_data".crypt" ] && {
      rm -rf ""$target_data".crypt"
    }
    print -n '' > ""$target_data".crypt"
    # open file descriptor for crypt data
    exec {cryptdat}> ""$target_data".crypt"
    # open file descriptor, read 1 byte at a time
    exec {filedat}< "$target_data"
    trap "exec {cryptdat}>&-; exec {filedat}<&-; return 1" INT TERM
    local key_counter=1
    set +o MULTIBYTE
    while sysread -i $filedat -s 1 char; do
      local keychar=$target_key[$key_counter]
      local conv=$(([##16]#char^#keychar))
      print -n -u$cryptdat -- "\x"${(l{2}{0})conv}""
      ((key_counter++))
      ((key_counter>target_key_ln)) && {
        new_key=''
        mutate_key "$target_key" "$dc_salt"
        target_key="$new_key"
        key_counter=1
      }
    done
    exec {cryptdat}>&-
    exec {filedat}<&-
    trap "return 1" INT TERM
    # if nodel not set + we have write perms, overwrite original file w/ crypt data & delete crypt file
    [[ "$nodel" != 1 ]] && [ -w "$target_data" ] && {
      exec {cryptdat}< ""$target_data".crypt"
      print -n '' > "$target_data"
      exec {filedat}> "$target_data"
      trap "exec {cryptdat}<&-; exec {filedat}>&-; return 1" INT TERM
      while sysread -i $cryptdat -s 1 char; do
        syswrite -o $filedat -- "$char"
      done
      exec {cryptdat}<&-
      rm -rf ""$target_data".crypt"
      exec {filedat}>&-
      trap "return 1" INT TERM
      ((keystream!=1)) && {
        ((no_write_salt)) && {
          rm -rf ""$target_data".salt"
        } || {
          print -rn -- "$dc_salt" > ""$target_data".salt"
        }
      }
    } || {
      ((keystream!=1)) && {
        ((no_write_salt)) && {
          rm -rf ""$target_data".crypt.salt"
        } || {
          print -rn -- "$dc_salt" > ""$target_data".crypt.salt"
        }
      }
    }
  # else if data isnt a file
  } || {
    local key_counter=1
    set +o MULTIBYTE
    int decrypt keyln
    ((keystream!=1)) && {
      ((decrypt)) && {
        ((keyln<0)) && keyln=8
        local dc_salt=${target_data::$keyln}
        target_data=${target_data:$keyln}
      } || {
        local dc_salt="$(gen_key 8)"
        print -rn -- "$dc_salt"
      }
    } || {
      ([ -z "$dc_salt" ] || ((dc_salt<8))) && {
        print "Error: received malformed salt"
        return 1
      }
    }
    mutate_key "$target_key" "$dc_salt"
    target_key="$new_key"
    while true; do
      local char=${target_data::1}
      local target_data=${target_data:1}
      [ -z "$char" ] && {
        break
      }
      local keychar=$target_key[$key_counter]
      local conv=$(([##16]#char^#keychar))
      print -n "\x"${(l{2}{0})conv}""
      ((key_counter++))
      ((key_counter>target_key_ln)) && {
        new_key=''
        mutate_key "$target_key" "$dc_salt"
        target_key="$new_key"
        key_counter=1
      }
    done
  }
}

do_mt_crypt() {
  setopt LOCAL_OPTIONS
  set +o MULTIBYTE
  zmodload zsh/zselect
  zmodload zsh/parameter
  local target_key="$1" target_data="$2" dc_salt
  int chunk_size="$3" worker_id is_file threadcount=$(($(nproc)+1)) decrypt keystream
  # set chunk size to 1048576 (1mb) if empty or less-than 0
  ([ -z "$chunk_size" ] || ((chunk_size<0))) && {
    ((chunk_size=1048576))
  }
  [ -z "$target_data" ] || [ -z "$target_key" ] && {
    print "Error: received insufficient input"
    print ""
    print "  usage: do_mt_crypt <target_key> <target_data>"
    return 1
  }
  # create working directory for process
  proc_id=$(mktemp -d /tmp/crypt_XXXXXXXX)
  trap "rm -rf $proc_id; return 1" INT TERM
  # read in target key if is file
  [ -f "$target_key" ] && {
    target_key=$(< "$target_key")
  }
  # if salt file exist, read in; else create
  [ -f ""$target_data".salt" ] && {
    dc_salt="$(< ""$target_data".salt")"
  } || {
    dc_salt="$(gen_key 8)"
  }
  # ensure target key is valid
  ([ -z "$target_key" ] || ((${#target_key}<8))) && {
    print "Error: received malformed key"
    return 1
  }
  # if target isn't a file, yes it is
  ! [ -f "$target_data" ] && {
    print -n '' > $proc_id/source_file
    chmod 0700 $proc_id/source_file
    exec {sourcefd}> $proc_id/source_file
    trap "exec {sourcefd}>&-; rm -rf $proc_id; return 1" INT TERM
    syswrite -o $sourcefd "$target_data"
    exec {sourcefd}>&-
    trap "rm -rf $proc_id; return 1" INT TERM
    target_data=$proc_id/source_file
  } || {
    ((is_file++))
  }
  # begin iterating over target file in chunks
  exec {sourcefd}< "$target_data"
  trap "exec {sourcefd}<&-; rm -rf $proc_id; return 1" INT TERM
  while sysread -i $sourcefd -s $chunk_size chunk; do
    print -n '' > $proc_id/$worker_id
    chmod 0700 $proc_id/$worker_id
    exec {chunkfd}> $proc_id/$worker_id
    trap "exec {chunkfd}>&-; exec {sourcefd}<&-; rm -rf $proc_id; return 1" INT TERM
    syswrite -o $chunkfd "$chunk"
    exec {chunkfd}>&-
    trap "exec {sourcefd}<&-; rm -rf $proc_id; return 1" INT TERM
    ((${#jobstates}>=threadcount)) && {
      until ((${#jobstates}<threadcount)); do
        zselect -t 0.1
      done
    }
    keystream=1 do_crypt "$target_key" $proc_id/$worker_id &
    ((worker_id++))
  done
  # wait for remaining jobs to complete
  until ((${#jobstates}==0)); do
    zselect -t 0.1
  done
  exec {sourcefd}<&-
  trap "rm -rf $proc_id; return 1" INT TERM
  ((is_file)) && {
    ! [ -w "$target_data" ] && {
      target_data=""$target_data".crypt"
    }
    print -n '' > "$target_data"
    exec {sourcefd}> "$target_data"
    trap "exec {sourcefd}>&-; rm -rf $proc_id; return 1" INT TERM
    # iterate over each output file and print in order
    for ((i=0; i<=$worker_id; i++)); do
      exec {chunkfd}< $proc_id/$i
      trap "exec {chunkfd}<&-; exec {sourcefd}>&-; rm -rf $proc_id; return 1" INT TERM
      sysread -i $chunkfd -s $chunk_size chunk
      syswrite -o $sourcefd "$chunk"
      exec {chunkfd}<&-
      trap "exec {sourcefd}>&-; rm -rf $proc_id; return 1"
    done
    exec {sourcefd}>&-
    trap "rm -rf $proc_id; return 1" INT TERM
    [ -f ""$target_data".salt" ] && {
      rm -rf ""$target_data".salt"
    } || {
      noglob print -rn -- "$dc_salt" > ""$target_data".salt"
    }
  } || {
    ((decrypt)) || {
      noglob print -rn -- "$dc_salt"
    }
    for ((i=0; i<=$worker_id; i++)); do
      exec {chunkfd}< $proc_id/$i
      trap "exec {chunkfd}<&-; rm -rf $proc_id; return 1" INT TERM
      sysread -i $chunkfd -s $chunk_size chunk
      noglob printf "%s" "$chunk"
      exec {chunkfd}<&-
      trap "rm -rf $proc_id; return 1" INT TERM
    done
  }
  rm -rf $proc_id
  return 0
}
