#!/usr/bin/env zsh

zmodload zsh/system

gen_key() {
  keyln=$1
  unset working_num_raw
  ([ -z "$keyln" ] || ! [[ $keyln =~ ^[0-9]+$ ]] || ((keyln<1))) && {
    keyln=128
  }
  genrnd_count=1
  exec {fd}< /dev/urandom
  while sysread -i $fd -s 1 working_num_raw; do
    grnd_out=$(printf "%02x" "'$working_num_raw")
    (((0x$grnd_out<0x20)) || ((0x$grnd_out>0x7e))) && {
      until (((0x$grnd_out>=0x20)) && ((0x$grnd_out<=0x7e))); do
        unset working_num_raw
        sysread -i $fd -s 1 working_num_raw
        grnd_out=$(printf "%02x" "'$working_num_raw")
      done
    }
    print -n "\x"$grnd_out""
    ((genrnd_count==keyln)) && {
      break
    }
    ((genrnd_count++))
  done
  exec {fd}<&-
  return 0
}

do_bitwise_xor() {
  a=$(printf "%02x" "'$1")
  b=$(printf "%02x" "'$2")
  conv=$(([##16]0x$a^0x$b))
  ((${#conv}<2)) && {
    conv="0"$conv""
  }
  print -n "\x"$conv""
}

do_crypt() {
  # fetch key name, error if key not exist
  target_key="$1"
  ! [ -f "$target_key" ] && {
    print "Error: key not exist"
    return 1
  }
  # read in target key from file (we can just use $(< $file) since we dont care about newline preservation on keyfile)
  target_key=$(< "$target_key")
  [ -z "$target_key" ] && {
    print "Error: provided key is empty"
    return 1
  }
  target_key_ln=${#target_key}
  # convert key to array
  unset cryptkey
  typeset -a cryptkey
  while true; do
    key_indice=${target_key::1}
    target_key=${target_key:1}
    [ -z "$key_indice" ] && {
      break
    }
    cryptkey+=("$key_indice")
  done
  # fetch target data, error if empty
  target_data="$2"
  [ -z "$target_data" ] && {
    print "Error: target data is empty!"
    return 1
  }
  # if data is file; read like one
  [ -f "$target_data" ] && {
    # create temp file for storing crypt data
    [ -f ""$target_data".crypt" ] && {
      rm -rf ""$target_data".crypt"
    }
    print -n '' > ""$target_data".crypt"
    # open file descriptor, read 1 byte at a time
    exec {filedat}< "$target_data"
    key_counter=1
    while sysread -i $filedat -s 1 char; do
      keychar=$cryptkey[$key_counter]
      do_bitwise_xor "$char" "$keychar" >> ""$target_data".crypt"
      ((key_counter++))
      ((key_counter>target_key_ln)) && {
        key_counter=1
      }
    done
    # if nodel not set, overwrite contents of original file with crypt data and delete crypt file
    [[ "$nodel" != 1 ]] && {
      exec {cryptdat}< ""$target_data".crypt"
      print -n '' > "$target_data"
      while sysread -i $cryptdat -s 1 char; do
        noglob printf "%s" "$char" >> "$target_data"
      done
      exec {cryptdat}<&-
      rm -rf ""$target_data".crypt"
    }
    exec {filedat}<&-
  # else if data isnt a file
  } || {
    key_counter=1
    while true; do
      char=${target_data::1}
      target_data=${target_data:1}
      [ -z "$char" ] && {
        break
      }
      keychar=$cryptkey[$key_counter]
      do_bitwise_xor "$char" "$keychar"
      ((keycounter++))
      ((keycounter>target_key_ln)) && {
        keycounter=1
      }
    done
  }
}

